specVersion: 0.0.1
description: ''
repository: ''
schema: ./schema.graphql
network:
  endpoint: wss://polkadot.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 7786000
    mapping:
      handlers:
        - handler: handleBond
          kind: substrate/EventHandler
          filter:
            module: staking
            method: bond
        - handler: handleReward
          kind: substrate/EventHandler
          filter:
            module: staking
            method: reward
        - handler: handleRewarded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: rewarded
        - handler: handleSlash
          kind: substrate/EventHandler
          filter:
            module: staking
            method: slash
        - handler: handleSlashed
          kind: substrate/EventHandler
          filter:
            module: staking
            method: slashed
        - handler: handleStakingReward
          kind: substrate/EventHandler
          filter:
            module: staking
            method: reward
        - handler: handleStakingRewarded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: rewarded
        - handler: handleStakingSlash
          kind: substrate/EventHandler
          filter:
            module: staking
            method: slash
        - handler: handleStakingSlashed
          kind: substrate/EventHandler
          filter:
            module: staking
            method: slashed